List Dependency Versions In About Dialog (#82)
* Flatten components.shared to components
* Flatten components.player to components
* Flatten components.header to components
* Flatten components.footer to components
* Flatten components.table to components
* Reformat components qmldir
* Sort requirements.txt
* Update dependencies
* Set dependency versions
* Move dependencies into separate tab
* Change order of tabs
* Move mpv and ffmpeg versions in to dependencies tab
* Increase icon size
* List dependencies
* Move dependencies out of model
* Uses pseudo table layout
* Remove spacer
* Rename dependency model to library model
* Simplify component
* Add other dependency category
* Edit padding
* Make translator credits a pseudo column layout
* Put people before code
* Use qt app version property
* Update model name

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -61,6 +61,40 @@ jobs:
           execute python -m pip install --upgrade pip
           execute python -m pip install wheel
           execute python -m pip install -r requirements.txt
+      - name: 'Set Dependency Versions'
+        run: |
+          function execute() { echo -e "\033[0;34m$*\033[0m"; "$@"; }
+          function error() { echo -e "\033[0;31m$*\033[0m"; }
+          
+          execute source venv/bin/activate
+          
+          DEPENDENCY_MODEL_FILE='MpvqcLibraryModel.qml'
+          DEPENDENCY_MODEL_PATH=$(find qml -type f -name "$DEPENDENCY_MODEL_FILE")
+          
+          if [ -z "$DEPENDENCY_MODEL_PATH" ]; then
+            error "Could not find dependency model $DEPENDENCY_MODEL_FILE"
+            exit 1
+          fi
+          
+          DEPENDENCIES=$(python -m pip list | tail -n +3)
+          BACKUP_IFS=$IFS
+          IFS=$'\n'
+          DEPENDENCIES=( $DEPENDENCIES )
+          IFS=$BACKUP_IFS
+          
+          for (( i=0; i<${#DEPENDENCIES[@]}; i++ )) do
+              LINE="${DEPENDENCIES[$i]}"
+              DEPENDENCY=$(echo "$LINE" | awk '{ print $1 }')
+              VERSION=$(echo "$LINE" | awk '{ print $2 }')
+              sed -i "s/@@pypi-$DEPENDENCY@@/$VERSION/g" "$DEPENDENCY_MODEL_PATH"
+          done
+          
+          if grep '@@' "$DEPENDENCY_MODEL_PATH"; then
+            error 'Could not find all dependency versions'
+            exit 1
+          else
+            execute cat "$DEPENDENCY_MODEL_PATH"
+          fi
       - name: 'Run Python Build'
         run: |
           function execute() { echo -e "\033[0;34m$*\033[0m"; "$@"; }
